### PR TITLE
Updating "Watir" project

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @dhamaniasad 

removing a dead project.

Cheers!

### CODE REVIEW

**Comment by dhamaniasad** [comment]
Hi @spekulatius ,

I would rather add an "obsolete" or "discontinued" section than remove the project altogether, as this project aims to catalog every single headless browser in existence.

**Comment by spekulatius** [comment]
Ah okay, sure. I can update it

**Comment by spekulatius** [comment]
Hey @dhamaniasad 

I've found the GitHub repo and updated the link to this one. Let me know if you need any more changes!

Cheers!

**Comment by spekulatius** [comment]
Hey @dhamaniasad 

just checking in: does this work for you now?

Cheers

**Pull request merged**
