### PR TITLE
suggest ViewFinder - head for headless browsers

### PR DESCRIPTION
**Pull request by i5ik**
This is probably rude to suggest as I'm the maker of ViewFinder, and I'm sure you think it's irrelevant here. Just saw your list on HN and thought this might be a useful addition for people looking to interact with headless browsers as if they were a normal *headful* browser.

### CODE REVIEW

**Comment by dhamaniasad** [comment]
Hi @i5ik ,

There is no problem with suggesting your own projects. Can you tell me a little bit more about the use-case? Am I able to see automated actions like with `headless: false` on puppeteer, or just open websites inside in the headless browser remotely and they’re streamed to my browser?

**Comment by i5ik** [comment]
Yes, you can connect to an existing browser, and also drive that browser with puppeteer, so you can see the automation. Or you can just run it and it will start its own browser and you can interact with the browser as if it were a normal browser, and, as you say, *open websites inside in the headless browser remotely and they’re streamed to my browser.* :)

I know you must be super busy and I know it's not your job to review all this stuff. I'm sorry I didn't explain it clearly in the above message. I greatly appreciate the quick reply @dhamaniasad, I'm sure VF probably isn't a fit for your list, but just thanks for reading this far!

**Comment by dhamaniasad** [comment]
I tried loading the demo at https://demo.browsergap.dosyago.com/ but its not working. When you say the content is streamed to my browser, is it streamed to a canvas / as a video? Or how does it provide the security aspect? We can probably put this in the Misc tools section.

**Comment by i5ik** [comment]
Hey @dhamaniasad oh thanks! I did not know I still had links to that demo. I'll try to find and remove them. I have shut down that demo for a long time and don't have any plans right not to revive it. Basically in order to try it out, you can follow one of the "Getting started" options, either Docker, binary download, npm download or cloning and installing. Anyway, I'm blown away by your responsiveness here and how you reviewed all this and found some errors like those old demo links I need to fix. Thank you so much. 

The content is streamed as a series of JPEG images, and technically you could use MJPEG, but we just send them over websocket, or webrtc (whichever is faster, at least in the pro version) and print them to a canvas. So you're right in that assumption and the reduction of the attack surface from "all of HTML, CSS and JS + a JS virtual machine" down to "JPEG" and a text only wire protocol to send the interactions back to the server to be run on the remote browser, is, as you say, how the security aspect is provided. This is the isolation model of remote browser isolation. 

I'm sure you must be really backed up, so no worried if you can't get to this. I'm just super happy and grateful you spent some time looking and it was great to chat with you! 😃

**Pull request closed without merging**
