### PR TITLE
Add awesome badge

### PR DESCRIPTION
**Pull request by phimage**
Then you or I can submit a PR to add to https://github.com/sindresorhus/awesome to give more visibility to your awesome list

### CODE REVIEW

**Comment by dhamaniasad** [comment]
The `awesome manifesto` states that:
"If you want your list to be included on awesome, try to only include actual awesome stuff in your list.      After all, it's a curation, not a collection."

This is a list of almost all headless browsers, and it is meant as a collection rather than a curation, so I think this list does not meet the requirements to be included in the awesome list. 

If the maintainers at `awesome` think otherwise, I will certainly proceed with the PR. 
I'll just mention @aleksandar-todorovic to see what his thoughts are, since he is a maintainer at `awesome`.

**Comment by aleksandar-todorovic** [comment]
Yup, @dhamaniasad is right. The point of the `awesome` collection is to include only awesome resources. As such, I think that this list will need to be reworked to be a part of the awesome list.

**Comment by phimage** [comment]
Ok!

**Comment by dhamaniasad** [comment]
I plan to keep this list the way it currently is, so I will go ahead and close this PR. Thanks @phimage and @aleksandar-todorovic!

**Pull request closed without merging**
